development:
  adapter: postgresql
  database: db_explorer
  username: diana
  password: 123456

test:
  adapter: postgresql
  database: db_explorer_test
  username: diana
  password: 123456

production:
  adapter: postgresql
  database: db_explorer
  username: diana
  password: 123456
development:
  adapter: postgresql
  database: share_development
  username: diana
  password: 123456

test:
  adapter: postgresql
  database: share_test
  username: diana
  password: 123456

production:
  adapter: postgresql
  database: share
  username: diana
  password: 123456
